version: '3'
services:
    mysql8:
        user: 1000:1000
        image: mysql:8
        restart: no # unless-stopped
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: my_app
            MYSQL_USER: my_app
            MYSQL_PASSWORD: secret
        volumes:
            - ./mysql-data:/var/lib/mysql
        ports:
            - '9306:3306'

    cakephp:
        user: 1000:1000
        image: webdevops/php-apache:8.3
        restart: no # unless-stopped
        container_name: cakephp
        working_dir: /application/webroot
        volumes:
            - ./web:/application
        environment:
            - WEB_DOCUMENT_ROOT=/application/webroot
            - DATABASE_URL=mysql://my_app:secret@mysql/my_app
        ports:
            - "8099:80"

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

